# Generated by Django 2.1.4 on 2019-01-05 15:34

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_add_story_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_story',
            name='image',
            field=models.ImageField(null=True, upload_to=diary.models.user_path),
        ),
        migrations.AddField(
            model_name='add_story',
            name='tumname_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
