# Generated by Django 2.1.4 on 2019-01-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20190106_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_story',
            name='tumname_image',
        ),
        migrations.AddField(
            model_name='add_story',
            name='tumnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
